#!/usr/bin/env python3
"""Proofline Studio OS — resource scoring + inventory generation.

Implements the Studio Readiness Score exactly as specified:

STUDIO READINESS SCORE =
  license x 0.20 + maintenance x 0.10 + documentation x 0.10 + accessibility x 0.15
+ performance x 0.10 + security x 0.10 + design_adaptability x 0.10
+ integration_simplicity x 0.05 + client_suitability x 0.05 + lean_fit x 0.05

Thresholds: >=8.0 APPROVED | 6.5-7.9 PILOT/POC | 4.0-6.4 REFERENCE ONLY | <4.0 AVOID

Score inputs are judgements grounded in the audit data in research/github-audit.csv,
the licence files fetched on 2026-09-23 and the cited sources in MASTER-REPORT.md.
Outputs: research/resource-inventory.csv, research/license-register.csv
"""
import csv, os

W = dict(license=.20, maintenance=.10, documentation=.10, accessibility=.15,
         performance=.10, security=.10, design=.10, integration=.05,
         client=.05, lean=.05)

# name, url, licence (human), spdx, audit/evidence, provides, gaps, risks, decision, notes,
# scores = [lic, maint, doc, a11y, perf, sec, design, integration, client, lean]
R = [
 # ---------- A. Strategy & copy ----------
 ("MECLABS Conversion Sequence Heuristic","https://content.marketingsherpa.com/data/public/LP-Exercise-WS.pdf",
  "Published research framework (citation only — no reuse grant)","citation-only",
  "Stable since ~2006; MECLABS Institute publishes the heuristic; no repo",
  "Weighted heuristic C = 4m+3v+2(i-f)-2a for diagnosis and prioritisation",
  "No templates, no forms, no measurable thresholds",
  "Article/PDF text is not licensed for reproduction or client hand-over",
  "REFERENCE","Use as mental model inside our teardown SKILL + template. Never copy text.",
  [6,8,6,5,5,8,7,9,7,9]),
 ("LIFT Model (Conversion.com / Goward 2009)","https://umbrex.com/resources/frameworks/marketing-frameworks/lift-model-for-conversion-value-relevance-clarity-anxiety-distraction-urgency/",
  "Published framework, third-party explanatory write-ups (no reuse grant)","citation-only",
  "Widely adopted CRO audit lens; stable, well documented by practitioners",
  "Six-factor audit lens: value, relevance, clarity, anxiety, distraction, urgency",
  "Not a deliverable format; no scoring rubric of its own",
  "Framework name/description must be quoted as reference, not copied wholesale",
  "ADOPT (as method)","Backbone of templates/teardown-report.md. Write our own wording.",
  [7,7,6,6,5,8,7,9,8,9]),
 ("NN/g: 5-second test + usability heuristics","https://www.nngroup.com/articles/five-second-testing/",
  "Copyrighted article (reference), method is public practice","citation-only",
  "NN/g publishes continuously; method is industry standard since the 1990s",
  "Cheap first-impression protocol (clarity/memorability) for hero validation",
  "No tooling; needs 5+ unmasked testers to be meaningful",
  "Article text is copyrighted — reference only",
  "ADOPT (as method)","Used in validation experiment #4 (mobile clarity) and in design-direction briefs.",
  [7,8,7,7,5,9,7,9,8,9]),
 ("TeardownHQ landing-page audit checklist","https://teardownhq.com/insights/landing-page-audit-checklist",
  "Commercial site + paid reports (reference only)","proprietary",
  "Actively published (2026); productised audit service",
  "21-checkpoint section-by-section audit structure; good coverage of objection handling",
  "Paid reports; no licence to reuse checklist text",
  "Copying their checklist text would be a copyright issue; also a competitor",
  "REFERENCE","Use to sanity-check our own teardown structure; author our own wording.",
  [5,7,6,5,5,7,6,9,5,7]),
 ("anthropics/skills — frontend-design + skill spec","https://github.com/anthropics/skills",
  "Apache-2.0 (example skills); document-skills source-available","Apache-2.0 / mixed",
  "177.8k stars; HEAD commit 2026-09-22; spec at agentskills.io",
  "Canonical SKILL.md format, YAML frontmatter, progressive disclosure, skill-creator",
  "No studio-specific opinion; generic design guidance; no QA gates",
  "Licence is MIXED: per-skill LICENSE files differ — verify before copying a skill folder",
  "ADOPT","Template for all our SKILL.md files. Copy only Apache-2.0 skill folders, keep NOTICE.",
  [8,10,9,6,6,8,7,9,8,10]),

 # ---------- B. Design intelligence ----------
 ("USWDS (U.S. Web Design System)","https://github.com/uswds/uswds",
  "Public domain (US Gov) + mixed third-party notices (Apache-2.0/OFL)","NOASSERTION",
  "7.2k stars; pushed 2026-09-23; federal programme with release cadence",
  "Production-tested accessible patterns, content style guide, design tokens",
  "US-centric content style; heavy; not a marketing-landing aesthetic",
  "Mixed third-party assets inside the repo (Font Awesome, Source Sans) — check per asset",
  "REFERENCE","Steal patterns (form errors, help text, focus), not code bulk.",
  [7,9,9,10,6,9,6,6,7,6]),
 ("GOV.UK Frontend","https://github.com/alphagov/govuk-frontend",
  "MIT","MIT","1.5k stars; pushed 2026-09-23; UK government service",
  "Gold-standard accessible form/error/button patterns and research-backed copy rules",
  "Government tone; not premium/editorial; no motion system",
  "Very low; MIT + excellent provenance",
  "REFERENCE","Borrow error-summary and field-level validation patterns for forms.",
  [9,9,9,10,8,10,5,6,6,6]),
 ("IBM Carbon Design System","https://github.com/carbon-design-system/carbon",
  "Apache-2.0","Apache-2.0","9.5k stars; pushed 2026-09-23; IBM-maintained",
  "Mature token architecture (colour, type, spacing), a11y docs per component",
  "Enterprise product UI, not conversion marketing; large surface",
  "Enterprise visual language; overweight for landing pages",
  "REFERENCE","Token naming taxonomy only.",
  [9,9,9,9,6,9,7,5,5,5]),
 ("Adobe React Aria / Spectrum","https://github.com/adobe/react-spectrum",
  "Apache-2.0","Apache-2.0","15.9k stars; pushed 2026-09-23; Adobe-maintained",
  "Best-in-class headless accessibility behaviour (focus, ARIA, i18n)",
  "No styling; bigger API surface than Base UI for our small needs",
  "Low; Apache-2.0. Learning curve if used instead of Base UI",
  "REFERENCE","Fallback primitive layer if Base UI regresses on a needed component.",
  [9,9,10,10,8,9,7,5,6,5]),
 ("Awwwards / Godly / Mobbin / Land-book (inspiration)","https://www.awwwards.com/",
  "Proprietary ToS; screenshots copyrighted by owners","proprietary",
  "Active commercial platforms",
  "Art-direction calibration, section-order patterns, layout vocabulary",
  "No licence to reuse screenshots or layouts; Mobbin/Land-book partly paid",
  "High trade-dress risk if used as 'copy this' input rather than pattern research",
  "REFERENCE (controlled intake only)","Only via templates/ design-direction brief; never paste screenshots into client files.",
  [3,7,6,3,4,5,7,6,4,6]),

 # ---------- C. UI primitives, components, templates ----------
 ("shadcn/ui","https://github.com/shadcn-ui/ui",
  "MIT","MIT","124.5k stars; pushed 2026-09-21; registry + CLI; Vercel-supported",
  "Copy-in React component source (Radix/Base UI primitives + Tailwind), themable via CSS vars",
  "Not an npm dependency (you own forks); no Astro-native components; no design opinion beyond defaults",
  "Default aesthetic is recognisable 'shadcn look' — needs deliberate art direction",
  "ADOPT (selective)","Install only the ~8 components we actually need into src/components/ui; pin registry hashes.",
  [10,9,9,8,7,9,8,8,9,9]),
 ("Base UI (@base-ui/react)","https://github.com/mui/base-ui",
  "MIT","MIT","11.0k stars; pushed 2026-09-23; v1.x stable, MUI full-time team; shadcn default since Jul 2026",
  "35 unstyled accessible primitives; active monthly releases; render-prop API",
  "Unstyled (expected); fewer ecosystem examples than Radix",
  "Low. Inherits MIT; keep version pins because APIs are still evolving post-1.0",
  "ADOPT","Primitive layer for Dialog/Popover/Tabs/Select/Accordion in React islands.",
  [10,9,8,9,9,9,8,7,9,9]),
 ("Radix Primitives","https://github.com/radix-ui/primitives",
  "MIT","MIT","19.3k stars; last push 2026-08-08 (slower cadence since WorkOS acquisition)",
  "Battle-tested primitives; largest ecosystem; what most shadcn code was written on",
  "Slower releases; complex components (Combobox) stalled",
  "Maintenance risk if new projects start here in 2026+",
  "REFERENCE / fallback","Only for existing client codebases that already use Radix.",
  [10,6,8,9,9,8,8,7,8,7]),
 ("Tailwind CSS","https://github.com/tailwindlabs/tailwindcss",
  "MIT","MIT","97.6k stars; pushed 2026-09-08; v4.3.x on npm (2026-09)",
  "Utility CSS + CSS-first @theme tokens; small output; no runtime",
  "Class-heavy markup; design tokens must be curated or output drifts generic",
  "Low; watch v4 upgrade churn in integrations (@astrojs/tailwind is deprecated — use @tailwindcss/vite)",
  "ADOPT","Only styling system. Tokens in @theme + CSS custom properties per design direction.",
  [10,9,9,8,9,9,8,9,9,10]),
 ("Astro","https://github.com/withastro/astro",
  "MIT","MIT","62.8k stars; pushed 2026-09-23; v7.3.4 on npm; Node >=22.12",
  "Static-first, zero-JS default, islands, image component, content collections",
  "Not a fit for app-like dashboards; smaller React-ecosystem gravity than Next",
  "Low. Major-version migration every ~12 months is real work for long-lived client sites",
  "ADOPT (V1 default framework)","Landing pages, marketing sites, blog. React islands only where interactive.",
  [10,10,9,9,10,9,8,8,9,10]),
 ("Next.js","https://github.com/vercel/next.js",
  "MIT","MIT","142.4k stars; pushed 2026-09-23; v16.3.x",
  "Full-stack React, SSR/ISR, routing, large ecosystem, best for app-like needs",
  "Heavier baseline JS/CWV risk; commercial hosting via Vercel Pro ($20/seat) only",
  "Framework churn (App Router, caching semantics) is a maintenance cost",
  "PILOT / fallback","Use only when the client needs auth, dashboards, ISR or CMS-in-Next (Payload).",
  [10,10,9,8,7,8,8,7,8,6]),
 ("AstroWind template","https://github.com/arthelokyo/astrowind",
  "MIT","MIT","~6k stars; Astro v7 + Tailwind v4 rewrite; active 2026",
  "Production-ready landing/marketing template: widgets, SEO metadata, blog, dark mode, image optimisation",
  "Generic brand feel out of the box; needs full token replacement; some widgets we will delete",
  "Template familiarity (many sites share its look) — must be art-directed, not shipped as-is",
  "ADAPT","V1 Master Site starts from it, then strip to ~10 sections and re-token everything.",
  [10,8,8,8,9,8,7,8,8,9]),
 ("Magic UI (shadcn registry)","https://github.com/magicuidesign/magicui",
  "MIT (LICENSE.md confirmed)","MIT","22.4k stars; pushed 2026-09-20",
  "150+ animated marketing components (marquee, bento, spotlight) as copy-in source",
  "Effects-first: many components are visual novelty with a11y/perf cost",
  "Magnet for 'AI slop' look; several effects ignore prefers-reduced-motion",
  "REFERENCE / selective ADAPT","Max 1–2 components per project, only after the Motion Budget allows it.",
  [10,9,7,4,4,8,7,8,6,7]),
 ("shadcn.io Pro Blocks","https://www.shadcn.io/license",
  "Proprietary; Individual licence forbids commercial/client use","proprietary",
  "Active commercial product (gated registry)",
  "Polished page blocks and marketing sections",
  "Commercial use requires Team/Org licence; redistribution restricted",
  "Buying an Individual seat and using it for client work would breach the licence",
  "AVOID (unless Team licence bought deliberately)","If ever adopted: Team licence, seats documented in licence-register.",
  [3,7,7,6,6,7,8,8,6,4]),
 ("Tailark / Aceternity / Shadcnblocks (freemium registries)","https://tailark.com/",
  "Freemium: free tier + paid all-access; terms vary per item","mixed",
  "Active commercial products",
  "Additional section patterns and effects for reference",
  "Paid tiers restrict redistribution; free tiers often require attribution or are non-commercial",
  "Mixed licences per block = audit burden with no strategic upside",
  "REFERENCE ONLY","Never ship a block whose licence we have not recorded in license-register.csv.",
  [4,7,6,5,5,6,7,7,5,5]),
 ("Headless UI","https://github.com/tailwindlabs/headlessui",
  "MIT","MIT","28.7k stars; last push 2026-04-13 (slower)",
  "Simple unstyled components, tight Tailwind fit",
  "Smaller component set than Base UI; slower cadence",
  "Maintenance signal weaker than Base UI in 2026",
  "REFERENCE","Not needed if Base UI is adopted.",
  [10,6,8,8,9,8,7,8,7,6]),

 # ---------- D. Motion & creative assets ----------
 ("Motion (ex-Framer Motion)","https://github.com/motiondivision/motion",
  "MIT","MIT","33.7k stars; pushed 2026-09-23; v13.x on npm",
  "Declarative React animation, AnimatePresence, layout/gesture APIs, reduced-motion support",
  "React-only (fine inside Astro islands); Motion+ premium content is separate (MIT code once bought)",
  "Bundle cost if used for micro-interactions CSS could do",
  "ADOPT (islands only)","Use for component-level motion in interactive islands; CSS for everything else.",
  [10,9,9,7,7,8,8,8,8,8]),
 ("GSAP 3.15 (Webflow)","https://gsap.com/community/standard-license/",
  "Standard 'no charge' licence (NOT open source); commercial use allowed","custom-free",
  "28.6k stars; npm 3.15.0; licence effective 2025-04-30, amended 2025-05-30",
  "Timeline control, ScrollTrigger, SplitText, MorphSVG — all free for commercial sites now",
  "Not OSI open source; prohibited in visual animation builders competing with Webflow; licence can change going forward",
  "Licence risk is *interpretive*, not zero: no redistribution as a builder product; no source ownership",
  "ADAPT (only if a project's motion brief exceeds Motion/CSS)","Keep GSAP behind one wrapper module; document licence in NOTICE + handover.",
  [7,8,7,8,8,8,9,7,7,7]),
 ("CSS + Web Animations API (baseline)","https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animations",
  "Web standard","n/a","Universal browser support; zero dependency",
  "Hover/focus/reveal transitions, view transitions, scroll-driven animations where supported",
  "No timeline orchestration; fancier sequences get verbose",
  "None; also the best reduced-motion story",
  "ADOPT (default)","First two rungs of the Motion Escalation Ladder are CSS-only.",
  [10,10,10,9,10,10,7,10,9,10]),
 ("Lottie / lottie-web","https://github.com/airbnb/lottie-web",
  "MIT","MIT","32.1k stars; last push 2025-09-01 (stale ~12 months)",
  "Plays After Effects JSON animation, designer-friendly pipeline",
  "JSON payloads bloat fast; runtime work on main thread; project effectively dormant",
  "Unmaintained + performance cost = poor fit for premium landing pages in 2026",
  "AVOID (new projects)","Legacy client files only.",
  [10,3,7,6,4,6,6,7,5,5]),
 ("Rive (runtime MIT + editor)","https://github.com/rive-app/rive-react",
  "Runtime MIT; editor commercial (Free/Cadet $9/Voyager $32 per seat)","MIT + SaaS",
  "1.2k stars (react binding); pushed 2026-09-16; runtimes maintained across platforms",
  "Interactive state-machine animation at very small file size; designer-editable",
  "Editor subscription for unlimited files; smaller ecosystem; needs a real motion brief to justify",
  "Editor is a paid SaaS with ToS — asset rights must be recorded; runtime itself is MIT",
  "PILOT","Only for one hero/interaction per project where interactivity earns its cost.",
  [8,8,7,7,9,8,9,5,6,4]),
 ("Three.js / React Three Fiber","https://github.com/pmndrs/react-three-fiber",
  "MIT","MIT","three 115.8k / R3F 32.4k stars; pushed 2026-09 (both active)",
  "3D, shaders, WebGL product visualisation",
  "Heavy GPU/JS cost, mobile battery drain, WebGL fallback burden",
  "Highest CWV/reliability risk of any option here; usually decoration, not conversion",
  "REFERENCE (only with a written business justification)","Requires explicit client sign-off + fallback poster image.",
  [10,9,8,6,4,7,9,4,4,3]),
 ("Lucide icons","https://github.com/lucide-icons/lucide",
  "ISC (LICENSE confirmed; some icons derived from Feather/MIT)","ISC",
  "24.7k stars; pushed 2026-09-22; active releases",
  "Consistent 1500+ icon set as inline SVG / tree-shakeable packages",
  "Single visual voice (geometric line) — limited for editorial/luxury directions",
  "Low; keep the Feather-derived notice file in the repo",
  "ADOPT","Default icon set; ship as inline SVG, never as an icon font or CDN link.",
  [10,9,9,8,9,9,7,9,8,10]),
 ("Google Fonts (self-hosted via Fontsource)","https://fontsource.org/",
  "Fonts are SIL OFL / Apache-2.0; Fontsource packages MIT","OFL-1.1/Apache-2.0",
  "Fontsource actively maintained; OFL fonts are a permanent grant",
  "Woff2 files + CSS we control, subset, self-hosted, GDPR-clean",
  "OFL requires keeping the licence file and (for some fonts) a reserved-name rule; no CDN",
  "Never load from fonts.googleapis.com/fonts.gstatic.com: LG München I (3 O 17493/20, 2022-01-20) ruled that unlawful; German mass-claim campaigns followed",
  "ADOPT (self-hosted only)","Font files in /public/fonts + LICENSE per family + preload for the display font.",
  [9,9,9,8,9,10,9,8,9,9]),
 ("Unsplash (free tier) + Unsplash+","https://unsplash.com/license",
  "Unsplash Licence (free, commercial OK, no attribution required); Unsplash+ has extra restrictions","custom",
  "Active platform; licence text updated over time",
  "Free high-quality photography for concept work and blogs",
  "No model-release verification and $0 indemnification; Unsplash+ forbids AI/ML use, digital-template use and shared asset storage",
  "Unsafe for client claims about people/products; + images cannot legally be fed to generative AI or shipped inside a template",
  "REFERENCE / ADAPT with strict rules","Only non-person, non-product imagery for concepts; every use logged in asset-provenance-log.csv with URL + date.",
  [6,8,7,7,8,5,7,9,5,8]),

 # ---------- E. Build, hosting, deployment ----------
 ("Cloudflare Pages / Workers / D1","https://developers.cloudflare.com/pages/platform/limits/",
  "Proprietary service (free + $5/mo Workers Paid); commercial use permitted on free plan","SaaS",
  "Unlimited static bandwidth on free tier; 500 builds/mo free; Workers Paid 10M req/mo for $5",
  "Static hosting + functions + KV/D1/R2 + previews, one account, cheap at studio scale",
  "D1/KV data residency is not a French/EU-pinned guarantee by default; support is community-tier on free",
  "Provider lock-in for functions (portable: static + Workers are standard-ish); DPA available",
  "ADOPT (V1 default host)","Client-owned Cloudflare account from day one; we get delegated access.",
  [9,9,8,8,10,8,7,9,9,10]),
 ("Netlify","https://www.netlify.com/pricing/",
  "Proprietary (free tier 300 credits/mo; Pro ~$20 flat since Apr 2026)","SaaS",
  "Mature JAMstack platform; flat Pro pricing with unlimited seats",
  "Static + functions + forms + deploy previews",
  "Free-tier credit exhaustion hard-stops sites; US-run",
  "Proprietary form handling ties client data to the platform",
  "REFERENCE / fallback host","Only if a client already lives there.",
  [8,9,9,8,9,8,7,9,8,7]),
 ("Vercel","https://vercel.com/docs/limits/fair-use-guidelines",
  "Proprietary; Hobby is non-commercial only, Pro $20/seat","SaaS",
  "Best-in-class Next.js DX",
  "Zero-config Next deploys, previews, ISR, image optimisation",
  "Hobby explicitly prohibits commercial use — a paid client build on Hobby breaches the fair-use policy",
  "Cost per seat + metered overage; strongest Next lock-in",
  "AVOID for client work (use only Pro, client-billed)","If a Next.js client insists: Pro seat billed to the client.",
  [6,9,9,8,8,8,8,9,7,5]),
 ("Hetzner / Scaleway / OVH VPS + Coolify","https://www.hetzner.com/cloud/",
  "Proprietary hosting; Coolify is Apache-2.0","SaaS + Apache-2.0",
  "€4–8/mo VPS class; EU jurisdictions (DE/FR)",
  "Full data residency, self-hosted Umami/Cal.com/Formbricks, Docker deploys",
  "You are the sysadmin: patching, backups, TLS, monitoring — unbilled hours",
  "Operational risk lands on the founder; a dead server is a dead client site",
  "PILOT (self-hosted path only)","Only for clients who buy a maintenance retainer.",
  [9,8,7,8,7,6,7,5,7,5]),
 ("GitHub (repos, Actions, Pages)","https://github.com/pricing",
  "Proprietary service (free tiers generous)","SaaS",
  "Industry default VCS; Actions minutes included",
  "Source of truth, PR previews (via host), CI for QA gates, client handover via ownership transfer",
  "Free private repos have limited Actions minutes; Pages is static-only and not ideal for client hosting",
  "Account/org ownership must be transferred or the client is locked out of their own site",
  "ADOPT","Every client project = its own repo; handover = GitHub org/repo transfer + write-up.",
  [9,10,10,8,8,8,8,9,9,10]),
 ("Keystatic (git-based CMS)","https://github.com/Thinkmill/keystatic",
  "MIT","MIT","2.4k stars; pushed 2026-09-08; local + GitHub modes",
  "Admin UI that commits MDX/JSON into the client's own repo — no database, no vendor",
  "No scheduling, no roles beyond GitHub, weak mobile editing, small ecosystem; version still 0.x",
  "0.x versioning means breaking changes; commit-based editing can confuse non-technical clients",
  "PILOT","Default CMS answer for clients who need editing; always with a 1-hour editor training.",
  [10,7,7,8,9,9,7,7,8,8]),
 ("Payload CMS v3","https://github.com/payloadcms/payload",
  "MIT","MIT","44.9k stars; pushed 2026-09-23; very active",
  "Code-first CMS inside Next.js: auth, access control, drafts, media, REST/GraphQL",
  "Requires a database + Next.js runtime → hosting cost and ops burden",
  "Overkill for a 6-section landing page; adds DB backups to the client contract",
  "PILOT (only for >€2,500 builds with real content ops)","Pair with Cloudflare/Postgres EU or client-owned DB.",
  [10,9,9,8,6,8,8,5,8,5]),
 ("Decap CMS","https://github.com/decaporg/decap-cms",
  "MIT","MIT","19.4k stars; pushed 2026-09-22 (steady, low velocity)",
  "Git-based editing UI, mature, works with static hosts",
  "YAML config sprawl, dated UX, limited workflows (documented third-party critique)",
  "Slower development pace since the rebrand; UX may frustrate clients",
  "REFERENCE","Keystatic preferred for new builds.",
  [10,6,7,8,9,8,6,7,7,7]),

 # ---------- F. Forms, CRM, scheduling ----------
 ("Tally (forms)","https://tally.so/",
  "Proprietary SaaS; Belgian company, EU servers; DPA built into ToS","SaaS",
  "Actively developed; free tier unlimited forms/submissions; Pro ~€20–29/mo",
  "Fastest path to a branded, conditional, file-upload intake or teardown-request form",
  "DPA is strongest on paid plans; embedded widgets can inject their own cookies/analytics",
  "Embed = third-party script on a privacy-sensitive page; free tier footer branding",
  "ADAPT (V1 fast path for intake/teardown forms)","Custom domain on Pro; consent copy in our own privacy notice; no embed on the main site hero.",
  [7,8,8,7,7,6,8,9,8,8]),
 ("Formbricks","https://github.com/formbricks/formbricks",
  "AGPL-3.0 core + /ee licence (LICENSE confirmed)","AGPL-3.0 + ee",
  "13.0k stars; pushed 2026-09-23; German vendor, EU cloud or self-host",
  "In-app/link surveys with self-hosting, data sovereignty",
  "AGPL obligations if we modify and serve it; survey-shaped, not long intake forms",
  "AGPL must be understood before shipping modifications for clients",
  "PILOT (self-hosted path)","Use unmodified, or keep modifications private in studio-only infra.",
  [6,9,7,8,7,8,7,5,7,5]),
 ("Cal.com (booking)","https://github.com/calcom/cal.com",
  "MIT (cloud plans paid; self-host free)","MIT + SaaS",
  "48.6k stars; pushed 2026-09-20; free cloud tier for 1 user",
  "Booking/qualification flow, calendar sync, EU self-host option, white-label on higher tiers",
  "Cloud tiers add up per seat; self-hosting needs a VPS + Postgres",
  "Third-party booking script = consent/DPA consideration; client wants bookings under their own domain",
  "ADAPT","Solo studio: free cloud tier first. Client-owned booking = them owning the Cal.com account.",
  [9,9,8,8,8,8,8,7,8,9]),
 ("Custom Worker + D1 form endpoint","(build) https://developers.cloudflare.com/workers/",
  "Our code (MIT-in-repo); Cloudflare service terms","build",
  "N/A — pattern is standard and well documented",
  "Zero-vendor form handling: validation, rate-limit, honeypot, D1 record, webhook, email",
  "We must build and maintain spam protection, deliverability, retries",
  "Deliverability and bounce handling are real operational work; EU email provider needed for notifications",
  "BUILD (V1 default for the Master Site)","90–150 LOC Worker + Turnstile; email via an EU transactional provider decided in POC-04.",
  [9,8,8,8,9,8,8,6,9,8]),

 # ---------- G. Analytics & CRO ----------
 ("Plausible Analytics","https://github.com/plausible/analytics",
  "AGPL-3.0 (self-host); cloud is a paid EU service from €9/mo","AGPL-3.0 + SaaS",
  "29.2k stars; pushed 2026-09-23; Estonian vendor, EU (Germany) hosting",
  "Cookieless, lightweight, honest dashboards; easy client handover; EU residency story",
  "Self-hosting needs ClickHouse + ~2GB RAM; cloud tiers price by pageviews",
  "AGPL: fine to run unmodified; modifications must be shared if served to others",
  "ADOPT (cloud, client-billed from €9/mo)","Client owns the account. Self-hosted Umami is the zero-cost alternative for studio-owned properties.",
  [8,9,9,8,10,8,8,9,9,9]),
 ("Umami","https://github.com/umami-software/umami",
  "MIT","MIT","39.0k stars; pushed 2026-09-22; cloud Hobby free (100k events, 3 sites)",
  "Simplest self-hostable analytics; event-metered; tiny script",
  "No funnels/revenue depth on entry tiers; US-operated cloud by default",
  "Cloud jurisdiction is US unless self-hosted",
  "ADAPT","Self-host on the same VPS as other studio tooling, or use Cloud Hobby for our own sites only.",
  [10,9,8,8,9,8,7,8,8,9]),
 ("Matomo (self-hosted)","https://github.com/matomo-org/matomo",
  "GPL-3.0","GPL-3.0","21.9k stars; pushed 2026-09-23; long-standing",
  "Reference implementation for CNIL-compliant consent-free measurement; on-prem, full data control",
  "PHP/MySQL stack; heavier; GPL obligations if modified and distributed",
  "Self-hosting burden; UI dated vs Plausible",
  "REFERENCE","Use as the compliance template (aggregate-only settings), not necessarily as the tool.",
  [6,9,9,8,7,7,6,5,7,5]),
 ("PostHog (EU cloud)","https://github.com/PostHog/posthog",
  "MIT core + /ee licence (confirmed); cloud paid","MIT + ee + SaaS",
  "39.9k stars; pushed 2026-09-23; EU cloud region available",
  "Funnels, session replay, experiments, flags — the complete CRO instrumentation",
  "Cookies/replay require consent; heavy for a €1,500 landing page; cost scales with events",
  "Session replay = high-risk personal data processing; needs a documented DPIA-ish rationale",
  "PILOT (only where the client funds measurement)","Never enable replay without signed consent + masking rules.",
  [7,9,9,8,6,7,9,6,7,5]),
 ("GrowthBook / Bayesian low-traffic testing (method)","https://www.growthbook.io/insights/when-not-to-run-test-product-leader-takeaways",
  "Open-source (MIT) platform; article as method reference","mixed",
  "Actively published; used by product teams",
  "Decision filter: will the result change an action; power/MDE; when NOT to test",
  "Not a substitute for traffic; no magic for <1,000 visits/month",
  "Running underpowered tests and calling them proof is a credibility risk",
  "ADOPT (as method)","Encoded as docs/07 + validation-experiment rules: no formal A/B under threshold.",
  [8,8,8,7,8,8,7,9,8,9]),

 # ---------- H. Accessibility, performance, SEO ----------
 ("axe-core (+ @axe-core/cli, Playwright integration)","https://github.com/dequelabs/axe-core",
  "MPL-2.0","MPL-2.0","7.5k stars; pushed 2026-09-22; npm 4.13.x; industry standard engine",
  "Automated WCAG rule engine; catches ~30–40% of issues; CI-able",
  "Cannot judge meaning, alt-text quality, focus order, or keyboard traps properly",
  "Automated-only testing is a *false assurance* risk — must be paired with manual gates",
  "ADOPT","Runs on every PR and in the launch receipt; results attached, not 'trusted'.",
  [9,9,9,10,9,9,6,9,9,10]),
 ("Pa11y CI","https://github.com/pa11y/pa11y",
  "LGPL-3.0","LGPL-3.0","4.5k stars; pushed 2026-09-21",
  "Simple CLI CI checks on URL lists with HTML reports",
  "Thin wrapper value over axe; LGPL adds notice obligations",
  "Duplicate of axe in our pipeline",
  "REFERENCE","Skip; axe + Playwright covers it.",
  [7,8,8,8,9,8,5,8,7,6]),
 ("Lighthouse / Lighthouse CI","https://github.com/GoogleChrome/lighthouse",
  "Apache-2.0","Apache-2.0","30.8k stars; pushed 2026-09-20",
  "Lab performance/a11y/SEO scoring; budget assertions in CI; Core Web Vitals lab proxies",
  "Lab scores ≠ field data; variance on shared CI runners",
  "Treating a 100 score as proof of real-user performance",
  "ADOPT","Budget assertion (perf ≥ 95 mobile lab, LCP ≤ 2.0s lab) as a launch gate; field data is the truth.",
  [9,9,9,9,10,9,7,9,9,10]),
 ("Playwright","https://github.com/microsoft/playwright",
  "Apache-2.0","Apache-2.0","96.6k stars; pushed 2026-09-23; npm 1.63.x",
  "Cross-browser (Chromium/Firefox/WebKit) automation: forms, keyboard sweeps, visual diffs, CWV traces",
  "Not a visual-regression suite out of the box (needs snapshot tuning)",
  "Test flakiness if over-scoped; keep the suite small",
  "ADOPT","One smoke suite per project: navigation, form submit, keyboard-only path, mobile viewport.",
  [10,10,9,9,9,9,7,7,9,9]),
 ("W3C WCAG 2.2 (incl. new AA criteria)","https://www.w3.org/TR/WCAG22/",
  "W3C document licence (free to reference/implement)","W3C",
  "W3C Recommendation; stable; 9 new SC vs 2.1, 4.1.1 removed",
  "Authoritative source for our a11y standard: 2.4.11 focus not obscured, 2.5.7 dragging, 2.5.8 target size 24×24, 3.2.6 consistent help, 3.3.7 redundant entry, 3.3.8 accessible auth",
  "It is a standard, not a test kit",
  "Claiming 'WCAG compliant' without a documented audit method is a credibility/legal risk",
  "ADOPT","docs/06 encodes the 6 new AA-relevant criteria as build-time rules + manual checks.",
  [10,10,10,10,8,9,7,9,9,9]),
 ("web.dev / Core Web Vitals thresholds","https://web.dev/articles/vitals",
  "Google documentation (reference)","reference",
  "Continuously updated; CrUX baseline ~55.9% of origins pass all three (May 2026)",
  "Field thresholds: LCP ≤2.5s, INP ≤200ms, CLS ≤0.1 at p75",
  "No tooling by itself",
  "None (documentation)",
  "ADOPT","docs/07 performance budget derives hard gates from these numbers.",
  [9,10,9,8,10,9,6,9,9,9]),

 # ---------- I. Privacy / AI / legal ----------
 ("CNIL — consent exemption for audience measurement","https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies-solutions-pour-les-outils-de-mesure-daudience",
  "Regulatory guidance (public)","regulatory",
  "Updated guidelines 2025-07-04; self-evaluation tool published",
  "Defines consent-free measurement: aggregate-only, first-party, no cross-site, 13-month tracker lifetime, 25-month retention, no data sharing",
  "Applies to measurement only — anything advertising/profiling needs consent",
  "Copying CNIL text as a client deliverable is not a licence; use it as a checklist",
  "ADOPT (as constraint)","docs/08 + docs/09 gate: no GA4, no pixels, no chat widget cookies without a CMP.",
  [9,9,9,8,8,9,6,8,9,9]),
 ("EU AI Act Article 50 (transparency)","https://www.jonesday.com/en/insights/2026/01/european-commission-publishes-draft-code-of-practice-on-ai-labelling-and-transparency",
  "Regulation (EU) 2024/1689 + draft labelling code","regulatory",
  "Article 50 obligations applicable from 2026-08-02; penalties up to €15m/3% turnover",
  "Deployer duty to disclose deepfakes/AI-manipulated content at first exposure; artistic/fictional works get attenuated disclosure; human editorial responsibility matters",
  "Not legal advice; Commission guidelines evolve; enforcement is per member state",
  "Shipping realistic AI imagery of people without disclosure is now a regulatory risk, not just an ethics issue",
  "ADOPT (as constraint + human gate)","docs/08: AI asset approval record + provenance log mandatory before any AI asset ships.",
  [9,9,8,7,8,9,6,8,9,8]),
 ("EU Omnibus Directive (fake reviews ban)","https://www.lexology.com/library/detail.aspx?g=929020b0-ff28-4964-a6fa-ad7f6edd2475",
  "Directive (EU) 2019/2161, in force since 2022-05-28","regulatory",
  "Enforced nationally; fines up to 4% of turnover or €2m",
  "Prohibits fake/incentivised-undisclosed reviews, deleting negative reviews, unfounded verification claims",
  "Does not tell us how to present real testimonials",
  "Any fabricated testimonial is now directly illegal in the EU, not merely unethical",
  "ADOPT (as constraint)","docs/11 + templates/case-study.md: testimonial permission + verbatim-only rule.",
  [9,9,8,7,7,9,6,9,9,9]),
 ("Loi LCEN — mentions légales (FR)","https://www.economie.gouv.fr/entreprises/developper-son-entreprise/innover-et-numeriser-son-entreprise/mentions-sur-votre-site-internet-les-obligations-respecter",
  "French statute art. 1-1/1-2 LCEN","regulatory",
  "In force; penalties reported up to €75k (physical) / €375k (legal persons)",
  "Mandatory publisher identity, publication director, host details, contact",
  "Does not cover GDPR obligations (separate notice required)",
  "Missing mentions légales in a client handover = client liability we created",
  "ADOPT (as build gate)","templates + QA checklist item; client signs off on their legal entity details.",
  [9,9,8,7,7,9,6,9,9,9]),
 ("Higgsfield Terms of Use + help centre (2026-07/08 update)","https://higgsfield.ai/creator-hub/help-center/account/who-owns-my-generations-and-can-i-use-them-commercially",
  "Proprietary SaaS terms (revised Jul 2026)","SaaS",
  "Terms revised July 2026 after public backlash; help-centre answers dated Aug 2026",
  "User keeps ownership of inputs/outputs, commercial use permitted, rights survive cancellation, client sublicensing allowed; licence to Higgsfield ends when content is deleted",
  "Non-Enterprise accounts: inputs are still used for training by default; IP indemnification only on Enterprise; no exclusivity guarantee; outputs may resemble others'",
  "Client-confidential material must never be uploaded: the data-use policy is incompatible with NDAs despite the July 2026 fix",
  "ADAPT (concept/asset layer only, hard gates)","docs/08 + prompts/: private workspace, no client assets, provenance record; human approval before any asset ships.",
  [5,8,7,6,7,6,9,7,7,7]),

 # ---------- J/K. Ops, portfolio, sales ----------
 ("OpenDesign (nexu-io/open-design)","https://github.com/nexu-io/open-design",
  "Apache-2.0 (LICENSE file confirmed)","Apache-2.0",
  "97.8k stars; HEAD commit 2026-09-23; 3.7k commits; local-first desktop app",
  "Agent-driven prototype/landing-page generation with real file output (HTML/PDF/PPTX/MP4)",
  "It is a design-agent harness, not a compliance or QA system; output still needs our gates",
  "Fast-moving repo (2.5k branches): pin a commit/tag; do not treat output as production code",
  "REFERENCE / PILOT for concept exploration","Use for early visual exploration only; everything it produces passes through our design + a11y gates.",
  [9,9,6,4,5,6,8,6,6,6]),
 ("VoltAgent/awesome-agent-skills (registry of skills incl. CRO/design skills)","https://github.com/VoltAgent/awesome-agent-skills",
  "Curated list; each listed skill has its own (often unclear) licence","mixed/unknown",
  "Actively maintained registry; 1,000+ entries",
  "Discovery surface for community SKILL.md files (frontend-design, CRO, taste/anti-slop)",
  "No licence normalisation: many entries have no explicit licence",
  "Shipping or adapting unlicensed skill text into a commercial deliverable = copyright exposure",
  "REFERENCE ONLY for discovery","Anything we like gets rewritten from scratch or verified to Apache-2.0/MIT first.",
  [4,8,6,5,5,5,7,7,6,7]),
 ("Case-study / credibility practice (own framework)","(build) docs/13 + templates/case-study.md",
  "Our own content","build","N/A",
  "Labelled concept work, permissioned client work, verbatim quotes, substantiation file per claim",
  "Not a substitute for real client outcomes",
  "Temptation to present concepts as client work — explicit disclosure rules required",
  "BUILD","Disclosure line rendered by default on every concept asset; unremovable without an approval record.",
  [10,8,8,8,8,8,8,9,10,9]),
]

def srs(s):
    keys=["license","maintenance","documentation","accessibility","performance","security","design","integration","client","lean"]
    return round(sum(s[i]*W[k] for i,k in enumerate(keys)),2)

def band(v):
    return ("APPROVED CANDIDATE" if v>=8.0 else "PILOT / POC REQUIRED" if v>=6.5 else "REFERENCE ONLY" if v>=4.0 else "REJECT / AVOID")

OUT=os.path.dirname(os.path.abspath(__file__))
inv = open(os.path.join(OUT,"resource-inventory.csv"),"w",newline="")
lic = open(os.path.join(OUT,"license-register.csv"),"w",newline="")
iw=csv.writer(inv); lw=csv.writer(lic)
iw.writerow(["resource","url","license","maintenance_evidence","what_it_provides","what_it_does_not_solve",
             "risks","readiness_score","band","decision","integration_notes"])
lw.writerow(["resource","url","license_declared","commercial_use","attribution_required","modification_redistribution",
             "trademark_notes","client_redistribution","status"])
for (name,url,license_,spdx,ev,prov,gaps,risks,dec,notes,s) in R:
    v=srs(s)
    iw.writerow([name,url,license_,ev,prov,gaps,risks,v,band(v),dec,notes])
    if spdx in ("MIT","Apache-2.0","ISC","MPL-2.0","LGPL-3.0","GPL-3.0","AGPL-3.0"):
        lw.writerow([name,url,spdx,"allowed","copyright notice in source","allowed (keep notices)",
                     "no trademark grant","allowed","OK — keep NOTICE file"])
    elif spdx=="OFL-1.1":
        lw.writerow([name,url,"OFL-1.1","allowed","font licence file must ship","allowed (reserved names apply)","none","allowed","OK — ship licence per family"])
    elif spdx in ("proprietary","SaaS","custom","mixed","mixed/unknown","NOASSERTION","W3C","citation-only","regulatory","reference","build"):
        status={"citation-only":"Reference only — do not reproduce text",
                "proprietary":"DO NOT SHIP until licence purchased/confirmed",
                "SaaS":"Service terms — read ToS + DPA before client use",
                "custom":"Custom licence — per-asset review required",
                "mixed":"Mixed licences — audit per file",
                "mixed/unknown":"UNKNOWN — DO NOT SHIP",
                "NOASSERTION":"Mixed/third-party — audit per file",
                "W3C":"Free to reference/implement",
                "regulatory":"Framework/regulation — reference only",
                "reference":"Documentation — reference only",
                "build":"Our own code — we own it"}[spdx]
        lw.writerow([name,url,license_,"see status","see status","see status","see status","see status",status])
inv.close(); lic.close()
print("resource-inventory.csv:",len(R),"rows | license-register.csv written")
for (n,_,_,_,_,_,_,_,_,_,sx) in sorted(R,key=lambda r:-srs(r[10])):
    print(f"  {srs(sx):4.2f}  {band(srs(sx)):24s} {n}")
